version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: examin-ai-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - examin-ai-net

  postgres:
    container_name: notification-service-db
    image: postgres
    environment:
      POSTGRES_DB: notification-service
      POSTGRES_USER: notification-service-user
      POSTGRES_PASSWORD: myPass
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - examin-ai-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U notification-service-user -d notification-service" ]
      interval: 5s
      timeout: 5s
      retries: 5

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: examin-ai-zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem # in-memory storage (dev only)
    networks:
      - examin-ai-net
    restart: unless-stopped

volumes:
  rabbitmq-data:
  postgres:

networks:
  examin-ai-net:
    driver: bridge
