spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    notification:
      exchanges:
        notificationExchange: "notification.exchange"
      queues:
        task: "notification.task"
        task-id: "notification.task.listener"
        error: "notification.error"
        error-id: "notification.error.listener"
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    from: hello@demomailtrap.co
    host: smtp.mailtrap.io
    port: 587
    username: 214bf150d2abab
    password: a71dd60964d824
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
server:
  port: 8050
management:
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
