spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  rabbitmq:
    notification:
      exchanges:
        notificationExchange: "notification.exchange"
      queues:
        exceptions-text: "exceptions.to.admins"
        exceptions-csv: "exceptions.to.admins.csv"
        task: "notification.task"
        task-id: "notification.task.listener"
        error: "notification.error"
        error-id: "notification.error.listener"
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: examinai.notifications@gmail.com
    password: wzmv wedc pnxa cpza
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    from: examinai.notifications@gmail.com
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
server:
  port: 8050
management:
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

#      wzmv wedc pnxa cpza
